// Code generated by go-swagger; DO NOT EDIT.

package connection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetconectionHandlerFunc turns a function with the right signature into a getconection handler
type GetconectionHandlerFunc func(GetconectionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetconectionHandlerFunc) Handle(params GetconectionParams) middleware.Responder {
	return fn(params)
}

// GetconectionHandler interface for that can handle valid getconection params
type GetconectionHandler interface {
	Handle(GetconectionParams) middleware.Responder
}

// NewGetconection creates a new http.Handler for the getconection operation
func NewGetconection(ctx *middleware.Context, handler GetconectionHandler) *Getconection {
	return &Getconection{Context: ctx, Handler: handler}
}

/*
	Getconection swagger:route GET /connection connection getconection

Getconection getconection API
*/
type Getconection struct {
	Context *middleware.Context
	Handler GetconectionHandler
}

func (o *Getconection) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetconectionParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
