// Code generated by go-swagger; DO NOT EDIT.

package connection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetconnectionbyidHandlerFunc turns a function with the right signature into a getconnectionbyid handler
type GetconnectionbyidHandlerFunc func(GetconnectionbyidParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetconnectionbyidHandlerFunc) Handle(params GetconnectionbyidParams) middleware.Responder {
	return fn(params)
}

// GetconnectionbyidHandler interface for that can handle valid getconnectionbyid params
type GetconnectionbyidHandler interface {
	Handle(GetconnectionbyidParams) middleware.Responder
}

// NewGetconnectionbyid creates a new http.Handler for the getconnectionbyid operation
func NewGetconnectionbyid(ctx *middleware.Context, handler GetconnectionbyidHandler) *Getconnectionbyid {
	return &Getconnectionbyid{Context: ctx, Handler: handler}
}

/*
	Getconnectionbyid swagger:route GET /connection/{id} connection getconnectionbyid

Getconnectionbyid getconnectionbyid API
*/
type Getconnectionbyid struct {
	Context *middleware.Context
	Handler GetconnectionbyidHandler
}

func (o *Getconnectionbyid) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetconnectionbyidParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
