// Code generated by go-swagger; DO NOT EDIT.

package connection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostconectionHandlerFunc turns a function with the right signature into a postconection handler
type PostconectionHandlerFunc func(PostconectionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostconectionHandlerFunc) Handle(params PostconectionParams) middleware.Responder {
	return fn(params)
}

// PostconectionHandler interface for that can handle valid postconection params
type PostconectionHandler interface {
	Handle(PostconectionParams) middleware.Responder
}

// NewPostconection creates a new http.Handler for the postconection operation
func NewPostconection(ctx *middleware.Context, handler PostconectionHandler) *Postconection {
	return &Postconection{Context: ctx, Handler: handler}
}

/*
	Postconection swagger:route POST /connection connection postconection

Postconection postconection API
*/
type Postconection struct {
	Context *middleware.Context
	Handler PostconectionHandler
}

func (o *Postconection) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostconectionParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
