// Code generated by go-swagger; DO NOT EDIT.

package connection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/webcustomerapi1/models"
)

// PostconectionOKCode is the HTTP code returned for type PostconectionOK
const PostconectionOKCode int = 200

/*
PostconectionOK returns a greeting

swagger:response postconectionOK
*/
type PostconectionOK struct {

	/*
	  In: Body
	*/
	Payload *models.Connection `json:"body,omitempty"`
}

// NewPostconectionOK creates PostconectionOK with default headers values
func NewPostconectionOK() *PostconectionOK {

	return &PostconectionOK{}
}

// WithPayload adds the payload to the postconection o k response
func (o *PostconectionOK) WithPayload(payload *models.Connection) *PostconectionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the postconection o k response
func (o *PostconectionOK) SetPayload(payload *models.Connection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostconectionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
