// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetconectionOKCode is the HTTP code returned for type GetconectionOK
const GetconectionOKCode int = 200

/*
GetconectionOK returns a greeting

swagger:response getconectionOK
*/
type GetconectionOK struct {

	/*contains the actual greeting as plain text
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetconectionOK creates GetconectionOK with default headers values
func NewGetconectionOK() *GetconectionOK {

	return &GetconectionOK{}
}

// WithPayload adds the payload to the getconection o k response
func (o *GetconectionOK) WithPayload(payload string) *GetconectionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the getconection o k response
func (o *GetconectionOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetconectionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
