// Code generated by go-swagger; DO NOT EDIT.

// Package restapi BOTBIO
//
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.0.1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//	  - text/plain
//
// swagger:meta
package restapi
