// Code generated by go-swagger; DO NOT EDIT.

package contact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetcontactbyidHandlerFunc turns a function with the right signature into a getcontactbyid handler
type GetcontactbyidHandlerFunc func(GetcontactbyidParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetcontactbyidHandlerFunc) Handle(params GetcontactbyidParams) middleware.Responder {
	return fn(params)
}

// GetcontactbyidHandler interface for that can handle valid getcontactbyid params
type GetcontactbyidHandler interface {
	Handle(GetcontactbyidParams) middleware.Responder
}

// NewGetcontactbyid creates a new http.Handler for the getcontactbyid operation
func NewGetcontactbyid(ctx *middleware.Context, handler GetcontactbyidHandler) *Getcontactbyid {
	return &Getcontactbyid{Context: ctx, Handler: handler}
}

/*
	Getcontactbyid swagger:route GET /contact/{id} contact getcontactbyid

Getcontactbyid getcontactbyid API
*/
type Getcontactbyid struct {
	Context *middleware.Context
	Handler GetcontactbyidHandler
}

func (o *Getcontactbyid) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetcontactbyidParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
