// Code generated by go-swagger; DO NOT EDIT.

package contact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/webcustomerapi1/models"
)

// GetcontactbyidOKCode is the HTTP code returned for type GetcontactbyidOK
const GetcontactbyidOKCode int = 200

/*
GetcontactbyidOK information connection

swagger:response getcontactbyidOK
*/
type GetcontactbyidOK struct {

	/*
	  In: Body
	*/
	Payload *models.Customer `json:"body,omitempty"`
}

// NewGetcontactbyidOK creates GetcontactbyidOK with default headers values
func NewGetcontactbyidOK() *GetcontactbyidOK {

	return &GetcontactbyidOK{}
}

// WithPayload adds the payload to the getcontactbyid o k response
func (o *GetcontactbyidOK) WithPayload(payload *models.Customer) *GetcontactbyidOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the getcontactbyid o k response
func (o *GetcontactbyidOK) SetPayload(payload *models.Customer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetcontactbyidOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
