// Code generated by go-swagger; DO NOT EDIT.

package contact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/webcustomerapi1/models"
)

// GetcontactOKCode is the HTTP code returned for type GetcontactOK
const GetcontactOKCode int = 200

/*
GetcontactOK returns a greeting

swagger:response getcontactOK
*/
type GetcontactOK struct {

	/*contains the actual greeting as plain text
	  In: Body
	*/
	Payload []*models.Contact `json:"body,omitempty"`
}

// NewGetcontactOK creates GetcontactOK with default headers values
func NewGetcontactOK() *GetcontactOK {

	return &GetcontactOK{}
}

// WithPayload adds the payload to the getcontact o k response
func (o *GetcontactOK) WithPayload(payload []*models.Contact) *GetcontactOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the getcontact o k response
func (o *GetcontactOK) SetPayload(payload []*models.Contact) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetcontactOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Contact, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
