// Code generated by go-swagger; DO NOT EDIT.

package contact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/webcustomerapi1/models"
)

// PutcontactbyidOKCode is the HTTP code returned for type PutcontactbyidOK
const PutcontactbyidOKCode int = 200

/*
PutcontactbyidOK information connection

swagger:response putcontactbyidOK
*/
type PutcontactbyidOK struct {

	/*
	  In: Body
	*/
	Payload *models.Contact `json:"body,omitempty"`
}

// NewPutcontactbyidOK creates PutcontactbyidOK with default headers values
func NewPutcontactbyidOK() *PutcontactbyidOK {

	return &PutcontactbyidOK{}
}

// WithPayload adds the payload to the putcontactbyid o k response
func (o *PutcontactbyidOK) WithPayload(payload *models.Contact) *PutcontactbyidOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the putcontactbyid o k response
func (o *PutcontactbyidOK) SetPayload(payload *models.Contact) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutcontactbyidOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
