// Code generated by go-swagger; DO NOT EDIT.

package produits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetproduitbyidHandlerFunc turns a function with the right signature into a getproduitbyid handler
type GetproduitbyidHandlerFunc func(GetproduitbyidParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetproduitbyidHandlerFunc) Handle(params GetproduitbyidParams) middleware.Responder {
	return fn(params)
}

// GetproduitbyidHandler interface for that can handle valid getproduitbyid params
type GetproduitbyidHandler interface {
	Handle(GetproduitbyidParams) middleware.Responder
}

// NewGetproduitbyid creates a new http.Handler for the getproduitbyid operation
func NewGetproduitbyid(ctx *middleware.Context, handler GetproduitbyidHandler) *Getproduitbyid {
	return &Getproduitbyid{Context: ctx, Handler: handler}
}

/*
	Getproduitbyid swagger:route GET /produits/{id} produits getproduitbyid

Getproduitbyid getproduitbyid API
*/
type Getproduitbyid struct {
	Context *middleware.Context
	Handler GetproduitbyidHandler
}

func (o *Getproduitbyid) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetproduitbyidParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
