// Code generated by go-swagger; DO NOT EDIT.

package produits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/webcustomerapi1/models"
)

// GetproduitbyidOKCode is the HTTP code returned for type GetproduitbyidOK
const GetproduitbyidOKCode int = 200

/*
GetproduitbyidOK information produits

swagger:response getproduitbyidOK
*/
type GetproduitbyidOK struct {

	/*
	  In: Body
	*/
	Payload *models.Produits `json:"body,omitempty"`
}

// NewGetproduitbyidOK creates GetproduitbyidOK with default headers values
func NewGetproduitbyidOK() *GetproduitbyidOK {

	return &GetproduitbyidOK{}
}

// WithPayload adds the payload to the getproduitbyid o k response
func (o *GetproduitbyidOK) WithPayload(payload *models.Produits) *GetproduitbyidOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the getproduitbyid o k response
func (o *GetproduitbyidOK) SetPayload(payload *models.Produits) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetproduitbyidOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
