// Code generated by go-swagger; DO NOT EDIT.

package produits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/webcustomerapi1/models"
)

// GetproduitsOKCode is the HTTP code returned for type GetproduitsOK
const GetproduitsOKCode int = 200

/*
GetproduitsOK returns a greeting

swagger:response getproduitsOK
*/
type GetproduitsOK struct {

	/*contains the actual greeting as plain text
	  In: Body
	*/
	Payload []*models.Produits `json:"body,omitempty"`
}

// NewGetproduitsOK creates GetproduitsOK with default headers values
func NewGetproduitsOK() *GetproduitsOK {

	return &GetproduitsOK{}
}

// WithPayload adds the payload to the getproduits o k response
func (o *GetproduitsOK) WithPayload(payload []*models.Produits) *GetproduitsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the getproduits o k response
func (o *GetproduitsOK) SetPayload(payload []*models.Produits) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetproduitsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Produits, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
