// Code generated by go-swagger; DO NOT EDIT.

package produits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetproduitsHandlerFunc turns a function with the right signature into a getproduits handler
type GetproduitsHandlerFunc func(GetproduitsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetproduitsHandlerFunc) Handle(params GetproduitsParams) middleware.Responder {
	return fn(params)
}

// GetproduitsHandler interface for that can handle valid getproduits params
type GetproduitsHandler interface {
	Handle(GetproduitsParams) middleware.Responder
}

// NewGetproduits creates a new http.Handler for the getproduits operation
func NewGetproduits(ctx *middleware.Context, handler GetproduitsHandler) *Getproduits {
	return &Getproduits{Context: ctx, Handler: handler}
}

/*
	Getproduits swagger:route GET /produits produits getproduits

Getproduits getproduits API
*/
type Getproduits struct {
	Context *middleware.Context
	Handler GetproduitsHandler
}

func (o *Getproduits) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetproduitsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
