// Code generated by go-swagger; DO NOT EDIT.

package produits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostproduitHandlerFunc turns a function with the right signature into a postproduit handler
type PostproduitHandlerFunc func(PostproduitParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostproduitHandlerFunc) Handle(params PostproduitParams) middleware.Responder {
	return fn(params)
}

// PostproduitHandler interface for that can handle valid postproduit params
type PostproduitHandler interface {
	Handle(PostproduitParams) middleware.Responder
}

// NewPostproduit creates a new http.Handler for the postproduit operation
func NewPostproduit(ctx *middleware.Context, handler PostproduitHandler) *Postproduit {
	return &Postproduit{Context: ctx, Handler: handler}
}

/*
	Postproduit swagger:route POST /produits produits postproduit

Postproduit postproduit API
*/
type Postproduit struct {
	Context *middleware.Context
	Handler PostproduitHandler
}

func (o *Postproduit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostproduitParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
