// Code generated by go-swagger; DO NOT EDIT.

package produits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/webcustomerapi1/models"
)

// PostproduitOKCode is the HTTP code returned for type PostproduitOK
const PostproduitOKCode int = 200

/*
PostproduitOK returns a greeting

swagger:response postproduitOK
*/
type PostproduitOK struct {

	/*
	  In: Body
	*/
	Payload *models.Produits `json:"body,omitempty"`
}

// NewPostproduitOK creates PostproduitOK with default headers values
func NewPostproduitOK() *PostproduitOK {

	return &PostproduitOK{}
}

// WithPayload adds the payload to the postproduit o k response
func (o *PostproduitOK) WithPayload(payload *models.Produits) *PostproduitOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the postproduit o k response
func (o *PostproduitOK) SetPayload(payload *models.Produits) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostproduitOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
