// Code generated by go-swagger; DO NOT EDIT.

package produits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// PutproduitsbyidURL generates an URL for the putproduitsbyid operation
type PutproduitsbyidURL struct {
	ID int64

	LinkPhoto            *string
	LinkPhotoEmplacement *string
	Nom                  *string
	Prix                 *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PutproduitsbyidURL) WithBasePath(bp string) *PutproduitsbyidURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PutproduitsbyidURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *PutproduitsbyidURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/produits/{id}"

	id := swag.FormatInt64(o.ID)
	if id != "" {
		_path = strings.Replace(_path, "{id}", id, -1)
	} else {
		return nil, errors.New("id is required on PutproduitsbyidURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var linkPhotoQ string
	if o.LinkPhoto != nil {
		linkPhotoQ = *o.LinkPhoto
	}
	if linkPhotoQ != "" {
		qs.Set("link_photo", linkPhotoQ)
	}

	var linkPhotoEmplacementQ string
	if o.LinkPhotoEmplacement != nil {
		linkPhotoEmplacementQ = *o.LinkPhotoEmplacement
	}
	if linkPhotoEmplacementQ != "" {
		qs.Set("link_photo_emplacement", linkPhotoEmplacementQ)
	}

	var nomQ string
	if o.Nom != nil {
		nomQ = *o.Nom
	}
	if nomQ != "" {
		qs.Set("nom", nomQ)
	}

	var prixQ string
	if o.Prix != nil {
		prixQ = *o.Prix
	}
	if prixQ != "" {
		qs.Set("prix", prixQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *PutproduitsbyidURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *PutproduitsbyidURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *PutproduitsbyidURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on PutproduitsbyidURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on PutproduitsbyidURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *PutproduitsbyidURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
