// Code generated by go-swagger; DO NOT EDIT.

package produits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/webcustomerapi1/models"
)

// PutproduitsbyidOKCode is the HTTP code returned for type PutproduitsbyidOK
const PutproduitsbyidOKCode int = 200

/*
PutproduitsbyidOK information connection

swagger:response putproduitsbyidOK
*/
type PutproduitsbyidOK struct {

	/*
	  In: Body
	*/
	Payload *models.Produits `json:"body,omitempty"`
}

// NewPutproduitsbyidOK creates PutproduitsbyidOK with default headers values
func NewPutproduitsbyidOK() *PutproduitsbyidOK {

	return &PutproduitsbyidOK{}
}

// WithPayload adds the payload to the putproduitsbyid o k response
func (o *PutproduitsbyidOK) WithPayload(payload *models.Produits) *PutproduitsbyidOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the putproduitsbyid o k response
func (o *PutproduitsbyidOK) SetPayload(payload *models.Produits) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutproduitsbyidOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
