// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/webcustomerapi1/models"
)

// GetcustomerbyidOKCode is the HTTP code returned for type GetcustomerbyidOK
const GetcustomerbyidOKCode int = 200

/*
GetcustomerbyidOK information connection

swagger:response getcustomerbyidOK
*/
type GetcustomerbyidOK struct {

	/*
	  In: Body
	*/
	Payload *models.Customer `json:"body,omitempty"`
}

// NewGetcustomerbyidOK creates GetcustomerbyidOK with default headers values
func NewGetcustomerbyidOK() *GetcustomerbyidOK {

	return &GetcustomerbyidOK{}
}

// WithPayload adds the payload to the getcustomerbyid o k response
func (o *GetcustomerbyidOK) WithPayload(payload *models.Customer) *GetcustomerbyidOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the getcustomerbyid o k response
func (o *GetcustomerbyidOK) SetPayload(payload *models.Customer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetcustomerbyidOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
