// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetcustomerHandlerFunc turns a function with the right signature into a getcustomer handler
type GetcustomerHandlerFunc func(GetcustomerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetcustomerHandlerFunc) Handle(params GetcustomerParams) middleware.Responder {
	return fn(params)
}

// GetcustomerHandler interface for that can handle valid getcustomer params
type GetcustomerHandler interface {
	Handle(GetcustomerParams) middleware.Responder
}

// NewGetcustomer creates a new http.Handler for the getcustomer operation
func NewGetcustomer(ctx *middleware.Context, handler GetcustomerHandler) *Getcustomer {
	return &Getcustomer{Context: ctx, Handler: handler}
}

/*
	Getcustomer swagger:route GET /customer customer getcustomer

Getcustomer getcustomer API
*/
type Getcustomer struct {
	Context *middleware.Context
	Handler GetcustomerHandler
}

func (o *Getcustomer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetcustomerParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
