// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/webcustomerapi/models"
)

// GetconnectionbyidOKCode is the HTTP code returned for type GetconnectionbyidOK
const GetconnectionbyidOKCode int = 200

/*
GetconnectionbyidOK information connection

swagger:response getconnectionbyidOK
*/
type GetconnectionbyidOK struct {

	/*
	  In: Body
	*/
	Payload *models.Connection `json:"body,omitempty"`
}

// NewGetconnectionbyidOK creates GetconnectionbyidOK with default headers values
func NewGetconnectionbyidOK() *GetconnectionbyidOK {

	return &GetconnectionbyidOK{}
}

// WithPayload adds the payload to the getconnectionbyid o k response
func (o *GetconnectionbyidOK) WithPayload(payload *models.Connection) *GetconnectionbyidOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the getconnectionbyid o k response
func (o *GetconnectionbyidOK) SetPayload(payload *models.Connection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetconnectionbyidOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
