// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetcustomerbyidHandlerFunc turns a function with the right signature into a getcustomerbyid handler
type GetcustomerbyidHandlerFunc func(GetcustomerbyidParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetcustomerbyidHandlerFunc) Handle(params GetcustomerbyidParams) middleware.Responder {
	return fn(params)
}

// GetcustomerbyidHandler interface for that can handle valid getcustomerbyid params
type GetcustomerbyidHandler interface {
	Handle(GetcustomerbyidParams) middleware.Responder
}

// NewGetcustomerbyid creates a new http.Handler for the getcustomerbyid operation
func NewGetcustomerbyid(ctx *middleware.Context, handler GetcustomerbyidHandler) *Getcustomerbyid {
	return &Getcustomerbyid{Context: ctx, Handler: handler}
}

/*
	Getcustomerbyid swagger:route GET /customer/{id} customer getcustomerbyid

Getcustomerbyid getcustomerbyid API
*/
type Getcustomerbyid struct {
	Context *middleware.Context
	Handler GetcustomerbyidHandler
}

func (o *Getcustomerbyid) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetcustomerbyidParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
