// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/webcustomerapi1/models"
)

// GetcustomerOKCode is the HTTP code returned for type GetcustomerOK
const GetcustomerOKCode int = 200

/*
GetcustomerOK returns a greeting

swagger:response getcustomerOK
*/
type GetcustomerOK struct {

	/*contains the actual greeting as plain text
	  In: Body
	*/
	Payload []*models.Connection `json:"body,omitempty"`
}

// NewGetcustomerOK creates GetcustomerOK with default headers values
func NewGetcustomerOK() *GetcustomerOK {

	return &GetcustomerOK{}
}

// WithPayload adds the payload to the getcustomer o k response
func (o *GetcustomerOK) WithPayload(payload []*models.Connection) *GetcustomerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the getcustomer o k response
func (o *GetcustomerOK) SetPayload(payload []*models.Connection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetcustomerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Connection, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
