// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostcustomerHandlerFunc turns a function with the right signature into a postcustomer handler
type PostcustomerHandlerFunc func(PostcustomerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostcustomerHandlerFunc) Handle(params PostcustomerParams) middleware.Responder {
	return fn(params)
}

// PostcustomerHandler interface for that can handle valid postcustomer params
type PostcustomerHandler interface {
	Handle(PostcustomerParams) middleware.Responder
}

// NewPostcustomer creates a new http.Handler for the postcustomer operation
func NewPostcustomer(ctx *middleware.Context, handler PostcustomerHandler) *Postcustomer {
	return &Postcustomer{Context: ctx, Handler: handler}
}

/*
	Postcustomer swagger:route POST /customer customer postcustomer

Postcustomer postcustomer API
*/
type Postcustomer struct {
	Context *middleware.Context
	Handler PostcustomerHandler
}

func (o *Postcustomer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostcustomerParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
