// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutconnectionbyidHandlerFunc turns a function with the right signature into a putconnectionbyid handler
type PutconnectionbyidHandlerFunc func(PutconnectionbyidParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutconnectionbyidHandlerFunc) Handle(params PutconnectionbyidParams) middleware.Responder {
	return fn(params)
}

// PutconnectionbyidHandler interface for that can handle valid putconnectionbyid params
type PutconnectionbyidHandler interface {
	Handle(PutconnectionbyidParams) middleware.Responder
}

// NewPutconnectionbyid creates a new http.Handler for the putconnectionbyid operation
func NewPutconnectionbyid(ctx *middleware.Context, handler PutconnectionbyidHandler) *Putconnectionbyid {
	return &Putconnectionbyid{Context: ctx, Handler: handler}
}

/*
	Putconnectionbyid swagger:route PUT /connection/{id} customer putconnectionbyid

Putconnectionbyid putconnectionbyid API
*/
type Putconnectionbyid struct {
	Context *middleware.Context
	Handler PutconnectionbyidHandler
}

func (o *Putconnectionbyid) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutconnectionbyidParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
