// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/webcustomerapi1/models"
)

// PutconnectionbyidOKCode is the HTTP code returned for type PutconnectionbyidOK
const PutconnectionbyidOKCode int = 200

/*
PutconnectionbyidOK information connection

swagger:response putconnectionbyidOK
*/
type PutconnectionbyidOK struct {

	/*
	  In: Body
	*/
	Payload *models.Connection `json:"body,omitempty"`
}

// NewPutconnectionbyidOK creates PutconnectionbyidOK with default headers values
func NewPutconnectionbyidOK() *PutconnectionbyidOK {

	return &PutconnectionbyidOK{}
}

// WithPayload adds the payload to the putconnectionbyid o k response
func (o *PutconnectionbyidOK) WithPayload(payload *models.Connection) *PutconnectionbyidOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the putconnectionbyid o k response
func (o *PutconnectionbyidOK) SetPayload(payload *models.Connection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutconnectionbyidOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
