// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/webcustomerapi1/models"
)

// PutcustomerbyidOKCode is the HTTP code returned for type PutcustomerbyidOK
const PutcustomerbyidOKCode int = 200

/*
PutcustomerbyidOK information connection

swagger:response putcustomerbyidOK
*/
type PutcustomerbyidOK struct {

	/*
	  In: Body
	*/
	Payload *models.Customer `json:"body,omitempty"`
}

// NewPutcustomerbyidOK creates PutcustomerbyidOK with default headers values
func NewPutcustomerbyidOK() *PutcustomerbyidOK {

	return &PutcustomerbyidOK{}
}

// WithPayload adds the payload to the putcustomerbyid o k response
func (o *PutcustomerbyidOK) WithPayload(payload *models.Customer) *PutcustomerbyidOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the putcustomerbyid o k response
func (o *PutcustomerbyidOK) SetPayload(payload *models.Customer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutcustomerbyidOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
