// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPutconnectionbyidParams creates a new PutconnectionbyidParams object
//
// There are no default values defined in the spec.
func NewPutconnectionbyidParams() PutconnectionbyidParams {

	return PutconnectionbyidParams{}
}

// PutconnectionbyidParams contains all the bound params for the putconnectionbyid operation
// typically these are obtained from a http.Request
//
// swagger:parameters putconnectionbyid
type PutconnectionbyidParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: query
	*/
	DateConnect *string
	/*
	  In: query
	*/
	IP *string
	/*ID of user in database
	  Required: true
	  In: path
	*/
	ID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutconnectionbyidParams() beforehand.
func (o *PutconnectionbyidParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qDateConnect, qhkDateConnect, _ := qs.GetOK("DateConnect")
	if err := o.bindDateConnect(qDateConnect, qhkDateConnect, route.Formats); err != nil {
		res = append(res, err)
	}

	qIP, qhkIP, _ := qs.GetOK("Ip")
	if err := o.bindIP(qIP, qhkIP, route.Formats); err != nil {
		res = append(res, err)
	}

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDateConnect binds and validates parameter DateConnect from query.
func (o *PutconnectionbyidParams) bindDateConnect(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.DateConnect = &raw

	return nil
}

// bindIP binds and validates parameter IP from query.
func (o *PutconnectionbyidParams) bindIP(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.IP = &raw

	return nil
}

// bindID binds and validates parameter ID from path.
func (o *PutconnectionbyidParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("id", "path", "int64", raw)
	}
	o.ID = value

	return nil
}
