// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutcustomerbyidHandlerFunc turns a function with the right signature into a putcustomerbyid handler
type PutcustomerbyidHandlerFunc func(PutcustomerbyidParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutcustomerbyidHandlerFunc) Handle(params PutcustomerbyidParams) middleware.Responder {
	return fn(params)
}

// PutcustomerbyidHandler interface for that can handle valid putcustomerbyid params
type PutcustomerbyidHandler interface {
	Handle(PutcustomerbyidParams) middleware.Responder
}

// NewPutcustomerbyid creates a new http.Handler for the putcustomerbyid operation
func NewPutcustomerbyid(ctx *middleware.Context, handler PutcustomerbyidHandler) *Putcustomerbyid {
	return &Putcustomerbyid{Context: ctx, Handler: handler}
}

/*
	Putcustomerbyid swagger:route PUT /customer/{id} customer putcustomerbyid

Putcustomerbyid putcustomerbyid API
*/
type Putcustomerbyid struct {
	Context *middleware.Context
	Handler PutcustomerbyidHandler
}

func (o *Putcustomerbyid) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutcustomerbyidParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
