// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Connection information connection
//
// swagger:model connection
type Connection struct {

	// DateConnect
	DateConnect string `json:"DateConnect,omitempty"`

	// id in database
	ID int64 `json:"ID,omitempty"`

	// idnav
	IP string `json:"Ip,omitempty"`
}

// Validate validates this connection
func (m *Connection) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this connection based on context it is used
func (m *Connection) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Connection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Connection) UnmarshalBinary(b []byte) error {
	var res Connection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
