// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Produits information clients
//
// swagger:model produits
type Produits struct {

	// link photo
	LinkPhoto string `json:"link_photo,omitempty"`

	// link photo emplacement
	LinkPhotoEmplacement string `json:"link_photo_emplacement,omitempty"`

	// nom
	Nom string `json:"nom,omitempty"`

	// prix
	Prix string `json:"prix,omitempty"`
}

// Validate validates this produits
func (m *Produits) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this produits based on context it is used
func (m *Produits) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Produits) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Produits) UnmarshalBinary(b []byte) error {
	var res Produits
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
